- name: Install Tmux on Debian/Ubuntu
  apt:
    name: tmux
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Install Tmux on CentOS/RHEL
  yum:
    name: tmux
    state: present
  when: ansible_facts['distribution'] in ['CentOS', 'Red Hat Enterprise Linux']

- name: Install TMUX
  homebrew:
    name: tmux
    state: present
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Clone TPM repository
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Temp Tmux.conf for Setup
  file:
    path: "$HOME/.tmux.conf"
    state: absent
  ignore_errors: true

- name: Symlink tmux.conf
  file:
    src: "{{playbook_dir}}/configs/tmux/tmux.conf"
    dest: "$HOME/.tmux.conf"
    state: link
