- name: Install Zsh on Debian/Ubuntu
  apt:
    name: zsh
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Install Zsh on CentOS/RHEL
  yum:
    name: zsh
    state: present
  become: true
  when: ansible_facts['distribution'] in ['CentOS', 'Red Hat Enterprise Linux']

- name: Install Zsh on macOS
  homebrew:
    name: zsh
    state: present
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Get information about ~/.oh-my-zsh folder
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_folder

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/bash
  when: not oh_my_zsh_folder.stat.exists

- name: Remove any Symlink of .alias
  file:
    path: "$HOME/.alias"
    state: absent
  ignore_errors: true

- name: Symlink alias
  file:
    src: "{{playbook_dir}}/configs/zsh/alias"
    dest: "$HOME/.alias"
    state: link

- name: Remove any Symlink of .zshrc
  file:
    path: "$HOME/.zshrc"
    state: absent
  ignore_errors: true

- name: Symlink zshrc
  file:
    src: "{{playbook_dir}}/configs/zsh/zshrc"
    dest: "$HOME/.zshrc"
    state: link

- name: Remove any Symlink of .local/bin
  file:
    path: "$HOME/.local/bin"
    state: absent
  ignore_errors: true

- name: Symlink zshrc
  file:
    src: "{{playbook_dir}}/configs/local/bin"
    dest: "$HOME/.local/bin"
    state: link
