- name: Clone fzf repository
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1

- name: Install FZF
  command: echo "y" | ~/.fzf/install
  args:
    executable: /bin/bash
