- name: Install jq on Debian/Ubuntu
  apt:
    name: jq
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Install jq on CentOS/RHEL
  yum:
    name: jq
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['CentOS', 'Red Hat Enterprise Linux']

- name: Install jq
  homebrew:
    name: jq
    state: present
  when: ansible_facts['distribution'] == 'MacOSX'