- name: Install i3 on Debian/Ubuntu
  apt:
    name: i3
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Install i3 on CentOS/RHEL
  yum:
    name: i3
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['CentOS', 'Red Hat Enterprise Linux']

- name: Install required packages
  apt:
    name:
      - autoconf
      - libconfuse-dev
      - libyajl-dev
      - libasound2-dev
      - libiw-dev
      - asciidoc
      - libpulse-dev
      - libnl-genl-3-dev
      - meson
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Install i3status on Debian/Ubuntu
  apt:
    name: i3status
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Install required packages (Red Hat-based)
  become: true
  become_method: sudo
  yum:
    name:
      - autoconf
      - confuse-devel
      - yajl-devel
      - alsa-lib-devel
      - iw-devel
      - asciidoc
      - pulseaudio-libs-devel
      - libnl3-devel
      - meson
    state: present
  when: ansible_facts['distribution'] in ['CentOS', 'Red Hat Enterprise Linux']

- name: Install i3status on CentOS/RHEL
  yum:
    name: i3status
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['CentOS', 'Red Hat Enterprise Linux']

- name: Install i3blocks on Debian/Ubuntu
  apt:
    name: i3blocks
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Install i3blocks on CentOS/RHEL
  yum:
    name: i3blocks
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['CentOS', 'Red Hat Enterprise Linux']

- name: Symlink i3
  file:
    src: "{{playbook_dir}}/configs/i3"
    dest: "$HOME/.config/i3"
    state: link
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu', 'CentOS', 'Red Hat Enterprise Linux']

- name: Symlink i3blocks
  file:
    src: "{{playbook_dir}}/configs/i3blocks"
    dest: "$HOME/.config/i3blocks"
    state: link
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu', 'CentOS', 'Red Hat Enterprise Linux']

- name: Symlink i3status
  file:
    src: "{{playbook_dir}}/configs/i3status"
    dest: "$HOME/.config/i3status"
    state: link
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu', 'CentOS', 'Red Hat Enterprise Linux']
