- name: Install exa on Debian/Ubuntu
  apt:
    name: exa
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Install exa on CentOS/RHEL
  yum:
    name: exa
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['CentOS', 'Red Hat Enterprise Linux']

- name: Install exa
  homebrew:
    name: exa
    state: present
  when: ansible_facts['distribution'] == 'MacOSX'
