- name: Add Alacritty PPA
  apt_repository:
    repo: ppa:aslatter/ppa
    state: present
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Update package list
  apt:
    update_cache: yes
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']


- name: Install Alacritty on Debian/Ubuntu
  apt:
    name: alacritty
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Install Alacritty on CentOS/RHEL
  yum:
    name: alacritty
    state: present
  when: ansible_facts['distribution'] in ['CentOS', 'Red Hat Enterprise Linux']


- name: Install Alacritty on MacOSX
  homebrew:
    name: alacritty
    state: present
  when: ansible_facts['distribution'] == 'MacOSX'
  ignore_errors: true
  register: alacritty_install_result

- name: Handle Alacritty installation error on MacOSX
  fail:
    msg: "{{ alacritty_install_result.msg }}"
  when: "'Warning: Not upgrading alacritty, the latest version is already installed' not in alacritty_install_result.msg"
  ignore_errors: true


- name: Remove any Symlink of alacrity
  file:
    path: "$HOME/.config/alacritty"
    state: absent
  ignore_errors: true

- name: Symlink alacritty.yml
  file:
    src: "{{ playbook_dir }}/configs/alacritty"
    dest: "$HOME/.config/alacritty"
    state: link
