- name: Add Wezterm GPG key
  ansible.builtin.apt_key:
    url: https://apt.fury.io/wez/gpg.key
    state: present
    keyring: /usr/share/keyrings/wezterm-fury.gpg
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Add Wezterm repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *'
    state: present
    filename: wezterm
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Update package list
  ansible.builtin.apt:
    update_cache: yes
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']


- name: Install wezterm on Debian/Ubuntu
  apt:
    name: wezterm
    state: present
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Install wezterm on CentOS/RHEL
  yum:
    name: wezterm
    state: present
  when: ansible_facts['distribution'] in ['CentOS', 'Red Hat Enterprise Linux']


- name: Install wezterm on MacOSX
  homebrew:
    name: wezterm
    state: present
  when: ansible_facts['distribution'] == 'MacOSX'


- name: Remove any Symlink of wezterm
  file:
    path: "$HOME/.wezterm.lua"
    state: absent
  ignore_errors: true

- name: Symlink wezterm.yml
  file:
    src: "{{ playbook_dir }}/configs/wezterm.lua"
    dest: "$HOME/.wezterm.lua"
    state: link
