[colors.bright]
black = "0x3e4452"
blue = "0x61afef"
cyan = "0x89dceb"
green = "0xa6e3a1"
magenta = "0xcba6f7"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xf9e2af"

[colors.normal]
black = "0x181825"
blue = "0x61afef"
cyan = "0x89dceb"
green = "0xa6e3a1"
magenta = "0xcba6f7"
red = "0xe06c75"
white = "0x5c6370"
yellow = "0xf9e2af"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[colors.selection]
background = "0x3e4452"
text = "CellForeground"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 15.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[scrolling]
history = 15000

[window]
opacity = 1.0

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bF"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bB"
