# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Ansible and Python dependencies
        uses: actions/cache@v2
        with:
            path: |
                ~/.ansible
                ~/.local/lib/python3.11/site-packages
            key: ${{ runner.os }}-ansible-python-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
             ${{ runner.os }}-ansible-python-

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
            python-version: '3.11' 

      - name: Install ansible
        run: python3 -m pip install --user ansible

      # Runs a set of commands using the runners shell
      - name: Run the playbook
        run: python3 -m ansible playbook  main.yml
